import { randomUUID } from "node:crypto";
import { pool } from "./index";
import type { BuildRecord, ProjectAnalysis, ProjectRecord } from "@workspace/shared";

type DbProject = { id: string; name: string; file_size: number; upload_status: ProjectRecord["uploadStatus"]; analysis_status: ProjectRecord["analysisStatus"]; upload_path: string | null; created_at: Date };
type DbBuild = { id: string; project_id: string; status: BuildRecord["status"]; progress: number; logs: string[]; error: string | null; artifact_id: string | null; created_at: Date };
const toProject = (p: DbProject): ProjectRecord => ({ id: p.id, name: p.name, fileSize: p.file_size, uploadStatus: p.upload_status, analysisStatus: p.analysis_status, createdAt: p.created_at.toISOString() });
const toBuild = (b: DbBuild): BuildRecord => ({ id: b.id, projectId: b.project_id, status: b.status, progress: b.progress, logs: b.logs ?? [], error: b.error, artifactId: b.artifact_id, createdAt: b.created_at.toISOString() });
export async function createProject(name: string) { const id = randomUUID(); const r = await pool.query<DbProject>("INSERT INTO projects (id,name) VALUES ($1,$2) RETURNING *", [id, name]); return toProject(r.rows[0]); }
export async function listProjects() { const r = await pool.query<DbProject>("SELECT * FROM projects ORDER BY created_at DESC"); return r.rows.map(toProject); }
export async function getProject(id: string) { const r = await pool.query<DbProject>("SELECT * FROM projects WHERE id=$1", [id]); return r.rows[0] ? toProject(r.rows[0]) : null; }
export async function getProjectSourcePath(id: string) { const r = await pool.query<{ upload_path: string | null }>("SELECT upload_path FROM projects WHERE id=$1", [id]); return r.rows[0]?.upload_path ?? null; }
export async function saveUpload(id: string, fileSize: number, uploadPath: string) { const r = await pool.query<DbProject>("UPDATE projects SET file_size=$2, upload_status='UPLOADED', upload_path=$3 WHERE id=$1 RETURNING *", [id, fileSize, uploadPath]); return toProject(r.rows[0]); }
export async function markAnalysisStatus(id: string, status: ProjectRecord["analysisStatus"]) { await pool.query("UPDATE projects SET analysis_status=$2 WHERE id=$1", [id, status]); }
export async function saveAnalysis(projectId: string, result: ProjectAnalysis) { await pool.query("INSERT INTO analysis_results (project_id,result) VALUES ($1,$2) ON CONFLICT (project_id) DO UPDATE SET result=excluded.result,created_at=now()", [projectId, JSON.stringify(result)]); }
export async function getAnalysis(projectId: string) { const r = await pool.query<{ result: ProjectAnalysis }>("SELECT result FROM analysis_results WHERE project_id=$1", [projectId]); return r.rows[0] ? { projectId, ...r.rows[0].result } : null; }
export async function createBuild(projectId: string) { const id = randomUUID(); const r = await pool.query<DbBuild>("INSERT INTO build_jobs (id,project_id,logs) VALUES ($1,$2,$3) RETURNING *", [id, projectId, JSON.stringify(["Build queued for the isolated Android worker."])]); return toBuild(r.rows[0]); }
export async function getBuild(id: string) { const r = await pool.query<DbBuild>("SELECT * FROM build_jobs WHERE id=$1", [id]); return r.rows[0] ? toBuild(r.rows[0]) : null; }
export async function updateBuild(id: string, fields: { status?: BuildRecord["status"]; progress?: number; error?: string | null; artifactId?: string | null }) { const sets: string[] = []; const values: unknown[] = [id]; for (const [key, value] of Object.entries(fields)) { const column = key === "artifactId" ? "artifact_id" : key; if (!/^(status|progress|error|artifact_id)$/.test(column)) throw new Error("Invalid build update field"); sets.push(`${column}=$${values.length + 1}`); values.push(value); } if (sets.length) await pool.query(`UPDATE build_jobs SET ${sets.join(",")} WHERE id=$1`, values); }
export async function appendBuildLog(id: string, line: string) { await pool.query("INSERT INTO build_logs (id,build_id,line) VALUES ($1,$2,$3)", [randomUUID(), id, line]); await pool.query("UPDATE build_jobs SET logs=(logs || $2::jsonb) WHERE id=$1", [id, JSON.stringify([line])]); }
export async function getBuildLogs(id: string) { const r = await pool.query<{ line: string }>("SELECT line FROM build_logs WHERE build_id=$1 ORDER BY created_at ASC,id ASC", [id]); return r.rows.map((x) => x.line); }
export async function createArtifact(input: { id: string; projectId: string; buildId: string; filename: string; path: string; size: number; sha256: string; applicationId: string | null }) { await pool.query("INSERT INTO artifacts (id,project_id,build_job_id,filename,file_path,size,sha256,application_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)", [input.id, input.projectId, input.buildId, input.filename, input.path, input.size, input.sha256, input.applicationId]); }
export async function getArtifact(id: string) { const r = await pool.query<{ file_path: string; filename: string }>("SELECT file_path,filename FROM artifacts WHERE id=$1", [id]); return r.rows[0] ?? null; }